services:
  backend:
    build: ./backend
    container_name: relt-backend
    restart: unless-stopped
    volumes:
      - relt-data:/app/data
    environment:
      - DATABASE_URL=sqlite:////app/data/relt.db
      - SECRET_KEY=C3ntr0M3d1c0V1l3ll4
    expose:
      - "8000"

  frontend:
    build: ./frontend
    container_name: relt-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  relt-data:
